Update automate-test.yml

diff --git a/.github/workflows/automate-test.yml b/.github/workflows/automate-test.yml
--- a/.github/workflows/automate-test.yml
+++ b/.github/workflows/automate-test.yml
@@ -14,6 +14,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    container: mcr.microsoft.com/playwright:v1.40.0 
 
     steps:
       - name: Checkout repository
@@ -28,7 +29,7 @@ jobs:
         run: npm install
 
       - name: Install Playwright Browsers
-        run: npx playwright install --with-deps
+        run: npx playwright install chromium
 
       - name: Run Playwright tests
         run: npx playwright test tests/todo/todo.spec.ts
@@ -48,8 +49,8 @@ jobs:
         if: ${{ github.event_name == 'pull_request' }}
         run: |
           if [[ "${{ job.status }}" == "success" ]]; then
-            echo "✅ Playwright Tests Passed!"
+            echo "Playwright Tests Passed!"
           else
-            echo "❌ Playwright Tests Failed!"
-            exit 1  # ❌ บล็อก PR ถ้า Playwright Fail
+            echo "Playwright Tests Failed!"
+            exit 1
           fi
